apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: translation-autoscaler
  namespace: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: translation
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 2
